//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManualAction.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionHistory
    {
        public System.Guid historyID { get; set; }
        public string manualActionID { get; set; }
        public string senderUser { get; set; }
        public string senderTeam { get; set; }
        public string receiverUser { get; set; }
        public string receiverTeam { get; set; }
        public string redirectedText { get; set; }
        public System.DateTime redirectedDate { get; set; }
    }
}
