//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManualAction.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualAction
    {
        public System.Guid manualActionID { get; set; }
        public string UY { get; set; }
        public string HTU { get; set; }
        public string material { get; set; }
        public string materialText { get; set; }
        public string MT { get; set; }
        public string amount { get; set; }
        public string brm { get; set; }
        public string priceBrm { get; set; }
        public string total { get; set; }
        public string DnmsMF { get; set; }
        public Nullable<decimal> DnmsMFValue { get; set; }
        public string orderValue { get; set; }
        public string productCode { get; set; }
        public string productCodeInfo { get; set; }
        public string productYear { get; set; }
        public Nullable<System.DateTime> registerDate { get; set; }
        public Nullable<System.DateTime> loginDate { get; set; }
        public string loginDateTime { get; set; }
        public string userRegisterNo { get; set; }
        public string username { get; set; }
        public string actionReason { get; set; }
        public string reasonDetail { get; set; }
        public Nullable<System.DateTime> madeDate { get; set; }
        public Nullable<int> statusType { get; set; }
        public string statusName { get; set; }
        public Nullable<bool> isRedirected { get; set; }
        public string historyID { get; set; }
        public string redirectedTeam { get; set; }
        public string redirectedUser { get; set; }
        public string redirectedText { get; set; }
        public Nullable<System.DateTime> redirectedDate { get; set; }
    }
}
