//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManualAction.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualActionReason
    {
        public System.Guid reasonID { get; set; }
        public string reasonName { get; set; }
    }
}
