//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManualAction.DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManualActionsDBEntities : DbContext
    {
        public ManualActionsDBEntities()
            : base("name=ManualActionsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActionHistory> ActionHistory { get; set; }
        public virtual DbSet<ManualActionReason> ManualActionReason { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<UserList> UserList { get; set; }
        public virtual DbSet<ManualAction> ManualAction { get; set; }
    }
}
